apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: {container_uri}
        #image: passfort-loggly
        #imagePullPolicy: Never
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: logglytoken
              key: token
        - name: NODE_HOSTNAME
          value: 'passfort'
        - name: LOGGLY_TAG
          value: docker,container
        ports:
        - containerPort: 24224
        volumeMounts:
        - name: varlog
          mountPath: /var/log/
        - name: varlogcontainers
          readOnly: true
          mountPath: /var/log/containers
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
